### ISSUE TITLE
Evaluate iOS 15+ issue with launch images

### ISSUE THREAD

**Issue by mrcgrtz** [mrcgrtz/create-launch-images#24]
Apparently the markup for launch images does not work anymore in iOS 15. Maybe the media queries need to be adjusted.

Tested with: iPhone 12 Pro, iOS 15.0.1 (19A348)

**Comment by Dreamseer** [comment]
The issue persists in iOS 15.1.1 (19B81).

If there is no fix on either my side or Apple’s side until iOS 16, I will deprecate this tool as Apple apparently abandoned `apple-touch-startup-image`.

**Comment by mrcgrtz** [comment]
See also: https://developer.apple.com/forums/thread/698389
